### PR TITLE
feat(all): remove yomiroll

### LINKED ISSUE #3052: After Update Still "List Empty Issue"
### Source information

Yomiroll 14.31

### Source language

All

### Steps to reproduce

- Ref.: to Issue #3049 

### Expected behavior

Loading the Anime

### Actual behavior

Video list is Empty error

### Aniyomi version

Preview r7513

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Secozzi**
Closes #3052

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by jmir1 — APPROVED** [review]
RIP

**Comment by PrimeTwister** [comment]
Reason?

**Comment by Secozzi** [comment]
Crunchyroll removed all non-drm streams

**Comment by blacktilebluewall** [comment]
I saw a github page talking bout to shift to vrm stuff..

**Comment by deepakdiplo** [comment]
Alternate

**Pull request merged**
