### PR TITLE
fix(id/minioppai): Migrate to Animestream + add search filters

### LINKED ISSUE #1422: Minioppai Does Not Show Any Anime
### Source information and language

Minioppai 13.3 (Indonesian/Indonesia)

### Steps to reproduce

1.Enter the Minioppai extension
2.Minioppai Extension Does Not Feature Any Anime

### Expected behavior

Should Show anime 

### Actual behavior

Does Not Feature Any Anime 

### Aniyomi version

Latest beta version

### Android version

11

### Other details

Screenshot_2023_0318_131206

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #1422 
i hate github.

Checklist:
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Secozzi** [comment]
Does this close #1422 ?

**Comment by Claudemirovsky** [comment]
> Does this close #1422 ?

YES, idk why this issue didn't appear when i searched (???????) but now it shows up just fine
cloudflare agents are trolling me

**Comment by Start38** [comment]
Are you still busy

**Comment by Start38** [comment]
> Apakah kamu masih sibuk

May I request an extension

**Comment by Secozzi** [comment]
@Start38 Please don't mention other sources that have nothing to do with the source the issue/pull request is about. This is the second time you've done this.

**Review by jmir1 — APPROVED** [review]

**Pull request merged**
