### PR TITLE
Update AnimeLatinoHD.kt

### PR DESCRIPTION
**Pull request by Dark25**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Dark25** [comment]
trying to get the video 😫

**Comment by Secozzi** [comment]
Did you really test this by compiling the extension through android studio? The branch name and commit indicates that this was made through github's web editor.

**Comment by Dark25** [comment]
> Did you really test this by compiling the extension through android studio? The branch name and commit indicates that this was made through github's web editor.

Yes, I am editing from android studio, only since it is only 1 file, I am adding it directly to github via web

**Comment by Dark25** [comment]
The only thing is that I'm having problems resolving the servers, it's my first collaboration here 😅

**Comment by Dark25** [comment]
reload

**Pull request closed without merging**
