### PR TITLE
Yomiroll: Adds on-going series

### PR DESCRIPTION
**Pull request by mklive**
Checks simulcast status to determine whether a series is ongoing or completed.

(Can't test the changes, waiting for @Samfun75 approval and testing)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Samfun75** [comment]
I don't think this is a good idea as Simulcast means the dub episodes are released at the same time as the subs and since the global update relies on the status to auto update it would be a ddos tool for newer anime like Chainsaw, Mob Psycho ... 

Since this mainly affects the global update, there are other solutions proposed in tachi that should be considered instead.
Do you guys agree @jmir1 @Quickdesh ?

**Comment by jmir1** [comment]
Doesn't the simulcast status still stay true when the anime is finished releasing?

So this property doesn't actually tell us anything about the current status of the anime...

(If I understood correctly)

**Comment by Samfun75** [comment]
> So this property doesn't actually tell us anything about the current status of the anime...

Correct. Like those two anime I mentioned.

**Comment by mklive** [comment]
> I don't think this is a good idea as Simulcast means the dub episodes are released at the same time as the subs and since the global update relies on the status to auto update it would be a ddos tool for newer anime like Chainsaw, Mob Psycho ...

Although it isn't an ideal solution (especially if it can be true for dub episodes), forcing Yomiroll users to disable "Skip for completed series" could have far worse implications if library is big an unnecessary requests are called.

> Since this mainly affects the global update, there are other solutions proposed in tachi that should be considered instead.

I'm open to any suggestions that would fit those requirements. 
So, what should be considered a series ongoing and it's completed?

**Comment by mklive** [comment]
> The solutions are not just for this extension but will affect the others too, like getting status from tracking services or manually allowing the user to set the status. They will have to be discussed tho, maybe join the Discord to discuss about this with the other

I don't have a discord account rn, I need to create it. A tracking server should be a better solution if aniyomi can provide an easy-to-use interface API for extensions, although it can be a point of failure if it's unreachable for unknown reasons. But, as you say, it needs to be discussed later. For now, I'm interested in getting this working using what the API could provide

**Comment by Samfun75** [comment]
Well I gave my opinion about this so its up to jmir...

**Comment by mklive** [comment]
> Doesn't the simulcast status still stay true when the anime is finished releasing?
> 
> So this property doesn't actually tell us anything about the current status of the anime...

About that, it isn't always the case: there is a 3 year seasons gap between finishing releasing and actually setting is_simulcast false but the majority would be COMPLETE and not ONGOING.

I'm about to building my changes on my end and setting this repo ready for review as soon as I finished testing

**Comment by mklive** [comment]
@jmir1 I've finally tested and now it's working as intended. A more accurate approach would be try to get last series season (and there there are some edge cases like AoT for example) and retrieve `is_simulcast` value.
I still think this is a better way than letting every series labeled as completed.

**Comment by jmir1** [comment]
> @jmir1 so... is there a particolar reason for this wait? testing? I've followed the checklist and it's ready to be merged. If there is some issue regarding this PR let me know asap

the issue is still that crunchyroll apparently does not supply any real information about the airing status of their anime.
so we shouldn't set the status to completed or ongoing, no matter the simulcast status.
it should always be unknown, imho.

**Comment by jmir1** [comment]
closing for insactivity

**Pull request closed without merging**
