### PR TITLE
fix(all/chineseanime): Update baseUrl + add StreamVid extractor

### LINKED ISSUE #2977: Chineseanime Not Working
### Source information

Chineseanime 14.6

### Source language

Multi

### Steps to reproduce

1. Open Chineseanime
2. Choose any of these Anime
Great Doctor Miss Nine, Make Money to be king, Xixing Ji Asura, Primordial Spiritual Lord
those are only few examples most anime don't work

### Expected behavior

to load the chosen episode

### Actual behavior

error: video list is empty

### Aniyomi version

Preview r7509

### Android version

Android 10

### Other details

it's been very long time since Chineseanime hasn't worked properly last several updates didn't fix it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #2977
^ Actually it doesn't, because `playlist-utils` got slightly _trolled_ recently, but everything should work well after _un-trolling_ `playlist-utils` :+1:

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by jmir1 — DISMISSED** [review]

**Comment by fakebhai** [comment]
won't it need to go override 9?

**Comment by Claudemirovsky** [comment]
> won't it need to go override 9? 

What

**Comment by fakebhai** [comment]
> > won't it need to go override 9? 
> 
> What

what jmir merged is override 6 and current latest version was 14.8 so it actually got downloaded I suppose



hence whoever updated extensions under this 1h won't get your fix

**Comment by jmir1** [comment]
> won't it need to go override 9?

should have been 7

**Comment by fakebhai** [comment]
> > won't it need to go override 9?
> 
> should have been 7

yeah didn't know this new multi-lib/theme stuff

**Pull request merged**
