### PR TITLE
fix(en/zoro): Update domain and fix the extractor

### PR DESCRIPTION
**Pull request by enimax-anime**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by jmir1 — COMMENTED** [review]
We should probably call the extension Aniwatch then.
And also drop the (experimental) thing and change the logo

**Comment by enimax-anime** [comment]
Ah, okay. I'll make those changes when I wake up :p

**Comment by Samfun75** [comment]
I think you also need to override the Id if extension is renamed, it's 6706411382606718900 for zoro

**Review by jmir1 — APPROVED** [review]

**Comment by jmir1** [comment]
Closes #1305

**Pull request merged**
