### PR TITLE
Updated Uhdmovies domain url

### PR DESCRIPTION
**Pull request by dvamshidhar**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Samfun75** [comment]
Closing as there is a domain override option in the extension's setting. No more updating extension for domain change.

**Comment by dvamshidhar** [comment]
Oops, added a branch commit to the pr

**Comment by jmir1** [comment]
Still, isn't it clever to update the domain anyway since some people have no idea how to change the URL in the settings/don't even know what the new URL is?

**Comment by Samfun75** [comment]
If they open the webview they will get redirected to the new domain, and shouldn't we encourage the users to use a feature specifically designed for this lol? if you think it's better this way, it can be updated I guess

**Pull request closed without merging**
