### PR TITLE
fix(id/otakudesu): Update baseUrl

### PR DESCRIPTION
**Pull request by willyreza**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Secozzi** [comment]
While we appreciate pull requests that fixes extensions, the changes must be tested. As this change was made through github's web editor, and that you've sent broken and untested pull requests before, I ask you to send a screen recording of you playing a video to show that you've built and tested the extension as you acknowledged in the checklist. Marking as draft until proof is sent

**Comment by willyreza** [comment]
https://github.com/aniyomiorg/aniyomi-extensions/assets/3974476/67e6f1b4-0e8f-4e08-a162-d72b3986bf89

I just change baseUrl from github. Thx

**Comment by Secozzi** [comment]
I know that you edited through GitHub, but you need to test and build your changes

**Comment by Secozzi** [comment]
Closing due to no response

**Pull request closed without merging**
