### PR TITLE
fix(multisrc/aniwatch/kaido): failed to extract video

### LINKED ISSUE #2568: AniWatch And Kaido: Failed to extract video.
### Source information

AniWatch 13.36 (English)

### Source language

English

### Steps to reproduce

1. Download the extension
2. Add an anime
3. Click on start to watch the anime

### Expected behavior

It should let me watch the anime

### Actual behavior

It goes back where we select episode and says Failed to extract video

### Aniyomi version

Preview r6691

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by J4zzyB1te7s**
fixes #2568
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by jmir1** [comment]
I don't understand, what does @theonlymo 's repo do differently?

**Comment by J4zzyB1te7s** [comment]
> I don't understand, what does @theonlymo 's repo do differently?

It updates the keys frequently

**Comment by jmir1** [comment]
thats insane
it runs every minute

**Comment by jmir1** [comment]
github free plan only has 2000 minutes included so you're gonna run out of your quota in about a day and a half

**Comment by J4zzyB1te7s** [comment]
> github free plan only has 2000 minutes included so you're gonna run out of your quota in about a day and a half

I have GitHub pro plan

**Comment by jmir1** [comment]
> > github free plan only has 2000 minutes included so you're gonna run out of your quota in about a day and a half
> 
> I have GitHub pro plan

BTW, I didn't know this, but there is no limit for public repositories :+1:

**Comment by J4zzyB1te7s** [comment]
#2721 seems better

**Pull request closed without merging**
